# Generated by Django 6.0 on 2025-12-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_number',
            field=models.IntegerField(default=10),
        ),
    ]
