# Generated by Django 6.0 on 2025-12-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_category_supplier_remove_product_supplier_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
