# Generated by Django 6.0 on 2025-12-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_seller_email_remove_seller_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='id_card_image',
        ),
        migrations.AddField(
            model_name='seller',
            name='id_card_number',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
