# Generated by Django 6.0 on 2025-12-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_seller_id_card_image_seller_id_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
