# Generated by Django 6.0 on 2025-12-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_sale_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
