# Generated by Django 6.0 on 2025-12-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_order_created_at_remove_order_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
